### ISSUE TITLE
Error when pretraining

### ISSUE THREAD

**Issue by ZhangZhuoSJTU** [zhangxiaochuan/MIRROR#1]
Hi,

Thanks for your excellent work. I am looking forward to playing with it.

However, when I follow the instructions in README, I encounter a _ValueError_ during `python pretrain.py`

Attached is the log.

```=bash
Traceback (most recent call last):
  File "pretrain.py", line 195, in <module>
    train_and_evaluate()
  File "pretrain.py", line 167, in train_and_evaluate
    transformer, train_data_iterator, optimizer, scheduler, params
  File "pretrain.py", line 33, in train
    preds = model(sources, source_pos, targets, target_pos)
  File "/.env/MIRROR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/MIRROR/networks.py", line 369, in forward
    dec_output, *_ = self.decoder(target_seq, target_pos, source_seq, enc_output)
  File "/.env/MIRROR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/MIRROR/networks.py", line 171, in forward
    dec_enc_attn_mask=dec_enc_attn_mask,
  File "/.env/MIRROR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/MIRROR/layers.py", line 41, in forward
    dec_output, enc_output, enc_output, mask=dec_enc_attn_mask)
  File "/.env/MIRROR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/MIRROR/sub_layers.py", line 65, in forward
    sz_b, len_k, _ = k.size()
ValueError: not enough values to unpack (expected 3, got 2)
```

A quick inspection into the code.  The decoder of Transformer outputs a singleton tensor with shape `[batch_size, seq_len_n, emb_dim_n]` when `return_attns` is not set.

https://github.com/zhangxiaochuan/MIRROR/blob/85a5bcd14b48899108e3415a7a82d278753a5987/networks.py#L102

But the Transformer model receives the output by unpacking a tuple. 

https://github.com/zhangxiaochuan/MIRROR/blob/85a5bcd14b48899108e3415a7a82d278753a5987/networks.py#L246

In this case, pytorch will unpack the returned tensor, incurring an incorrect shape error (the shape of `enc_output` mistakenly becomes `[seq_len_n, emb_dim_n]`). 

The following example code illustrates what happen there.

```python
t = torch.ones(123, 456, 789)
x, *_ = t
print(x.size()) # output: torch.Size([456, 789])
```

I am using python 3.6 and pytorch 1.10.0+cu102. The bug may not be reproduced in other environments.

I may also be wrong when reasoning the root cause. Please kindly let me know how to fix the issues.

Best

**Comment by zhangxiaochuan** [comment]
[2eea89e](https://github.com/zhangxiaochuan/MIRROR/commit/2eea89e8f7969e3c29495ad0b8e1b5b8bcb4d782) fixed is issue.
